global:
  scrape_interval: 5s 
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "prometheus" 
    static_configs:
      - targets: ["localhost: 9090" ]

  - job_name: "fastapi" 
    static_configs:
      - targets: ["127.0.0.1:8000" ] 
